/* ======================================================================
   PRECISION TOUCH · independent pointers, cleaner response, live feedback
   ====================================================================== */
const TOUCH_CONTROL_VERSION=3,precisionTouchPointers={};
function installPrecisionTouch(){
 if(T('touchControls')?.dataset.precision===String(TOUCH_CONTROL_VERSION))return;const controls=T('touchControls');controls.dataset.precision=String(TOUCH_CONTROL_VERSION);
 const style=document.createElement('style');style.textContent=`
html,body{overscroll-behavior:none}body.touch{touch-action:none;-webkit-user-select:none;user-select:none}body.touch #cv{touch-action:none}
#touchControls{--touch-size:132px;--touch-knob:54px;contain:layout style;transition:opacity .18s ease}
#moveStickWrap{left:max(22px,calc(env(safe-area-inset-left) + 14px))}#aimStickWrap{right:max(22px,calc(env(safe-area-inset-right) + 14px))}
.touch-stick-wrap{width:calc(var(--touch-size) + 24px);height:calc(var(--touch-size) + 38px);bottom:max(18px,calc(env(safe-area-inset-bottom) + 10px))}
.touch-stick{width:var(--touch-size);height:var(--touch-size);overflow:visible;border:2px solid #8fa9b65c;background:radial-gradient(circle at 50% 50%,#30455c52 0 18%,#162637cf 20% 53%,#070d17e8 55% 100%);box-shadow:inset 0 0 0 8px #c9e4ef08,inset 0 0 32px #6ec2dd19,0 8px 34px #000c}
.touch-stick:before{inset:13px;border-color:#c9d9df39}.touch-stick-grid{left:14px;right:14px;background:linear-gradient(90deg,transparent,#c9d9df45,transparent)}
.touch-knob{width:var(--touch-knob);height:var(--touch-knob);margin:calc(var(--touch-knob) / -2);will-change:transform;transition:transform .035s linear,box-shadow .08s;background:radial-gradient(circle at 36% 30%,#f8e5aa,#c09a5e 21%,#4c6576 25%,#1b2d3e 62%,#080f19 66%);box-shadow:0 0 0 6px #d5e6e920,0 7px 17px #000b,0 0 24px #76c5dd20}
#aimStick{border-color:#dfa96e6e;background:radial-gradient(circle at 50% 50%,#71482d40 0 18%,#2d2422d9 20% 53%,#0b0d14eb 55% 100%)}#aimStick:before{border-color:#ffd09b42}#aimStick .touch-stick-grid{background:linear-gradient(90deg,transparent,#ffd09b45,transparent)}#aimStick .touch-knob{background:radial-gradient(circle at 50% 50%,#fff7d8 0 8%,#f2a356 10% 23%,#69422f 25%,#2a2528 31% 62%,#0b0d14 66%);box-shadow:0 0 0 6px #f0b36f24,0 7px 17px #000b,0 0 27px #ef9c4b2b}
.touch-stick.active{transform:scale(1.025);border-color:#d8eef2b0}.touch-stick.active .touch-knob{box-shadow:0 0 0 7px #e9f6f53b,0 6px 17px #000c,0 0 34px #9feaff62}#aimStick.active{border-color:#ffd092c4}#aimStick.active .touch-knob{box-shadow:0 0 0 7px #ffe1ae3d,0 6px 17px #000c,0 0 35px #ffac576b}
.touch-caption{height:30px;font-size:8px;color:#91a8b4;letter-spacing:.13em}.touch-caption b{color:#f0d59a}.touch-caption .touch-power{width:24px;height:2px;background:#65758242;position:relative}.touch-caption .touch-power:after{content:'';position:absolute;inset:0;transform-origin:left;transform:scaleX(var(--power,0));background:#f0cb80;box-shadow:0 0 8px #edb55d;transition:transform .04s linear}
.touch-actions{right:max(calc(var(--touch-size) + 47px),calc(env(safe-area-inset-right) + var(--touch-size) + 37px));bottom:max(23px,calc(env(safe-area-inset-bottom) + 15px));grid-template-columns:repeat(2,64px);gap:10px}
.touch-action{--ready:1;position:relative;width:64px;height:64px;overflow:visible;border:1px solid #d7c1857a;background:radial-gradient(circle at 38% 27%,#36485ce8,#111c2aef 66%,#060b13f5);font-size:7px;box-shadow:inset 0 0 0 5px #d8c3860b,0 7px 20px #000a;isolation:isolate}
.touch-action:before{content:'';position:absolute;inset:-4px;border-radius:inherit;background:conic-gradient(#f0c775 calc(var(--ready) * 1turn),#43526366 0);-webkit-mask:radial-gradient(farthest-side,transparent calc(100% - 3px),#000 0);mask:radial-gradient(farthest-side,transparent calc(100% - 3px),#000 0);opacity:.75;pointer-events:none}.touch-action:after{content:'';position:absolute;inset:5px;border:1px solid #ffffff0b;border-radius:inherit;pointer-events:none}
.touch-action strong{font-size:15px;margin-bottom:1px}.touch-action .touch-name{display:block;max-width:58px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.touch-action .touch-state{display:block;margin-top:2px;color:#8fa3b4;font:700 6px system-ui;letter-spacing:.08em}.touch-action.ready .touch-state{color:#efd59b}.touch-action.pressed{transform:scale(.88);filter:brightness(1.35)}.touch-action.cooling{opacity:.62;filter:saturate(.62)}.touch-action.cooling:before{opacity:.48}.touch-action.interact{border-radius:14px 50% 50% 50%}
.touch-fire-ring{inset:18px;border-color:#f0a35965;animation-duration:11s}.touch-stick.active .touch-fire-ring{border-style:solid;box-shadow:0 0 16px #ee9e4b27}
body.touch.touch-aiming #touchControls{opacity:.96}body.touch.touch-aiming #aimStickWrap{filter:brightness(1.12)}body.touch.touch-moving #moveStickWrap{filter:brightness(1.08)}
@media(max-width:880px){#touchControls{--touch-size:116px;--touch-knob:48px}.touch-actions{grid-template-columns:repeat(2,56px);right:max(calc(var(--touch-size) + 33px),calc(env(safe-area-inset-right) + var(--touch-size) + 25px));gap:8px}.touch-action{width:56px;height:56px}.touch-action strong{font-size:13px}.touch-action .touch-name{max-width:50px}body.touch #botL{bottom:152px}body.touch #botC{bottom:max(150px,calc(env(safe-area-inset-bottom) + 142px))}}
@media(max-height:560px) and (orientation:landscape){#touchControls{--touch-size:98px;--touch-knob:42px}.touch-stick-wrap{height:126px;bottom:max(8px,env(safe-area-inset-bottom))}.touch-caption{height:22px;font-size:6px}.touch-actions{grid-template-columns:repeat(2,49px);right:max(calc(var(--touch-size) + 29px),calc(env(safe-area-inset-right) + var(--touch-size) + 20px));bottom:max(10px,calc(env(safe-area-inset-bottom) + 5px));gap:6px}.touch-action{width:49px;height:49px}.touch-action strong{font-size:11px}.touch-action .touch-state{display:none}body.touch #botL,body.touch #botC{display:none}}
@media(max-width:540px) and (orientation:portrait){#touchControls{--touch-size:102px;--touch-knob:44px}.touch-stick-wrap{bottom:max(12px,calc(env(safe-area-inset-bottom) + 7px))}#moveStickWrap{left:max(8px,calc(env(safe-area-inset-left) + 5px))}#aimStickWrap{right:max(8px,calc(env(safe-area-inset-right) + 5px))}.touch-actions{right:max(9px,calc(env(safe-area-inset-right) + 6px));bottom:max(132px,calc(env(safe-area-inset-bottom) + 126px));grid-template-columns:repeat(2,52px);gap:7px}.touch-action{width:52px;height:52px}.touch-caption{font-size:6px}.touch-caption .touch-power{display:none}body.touch #botC{bottom:252px}body.touch #botL{bottom:142px;max-width:150px}}
`;(document.head||document.body).appendChild(style);
 for(const id of ['moveStick','aimStick']){const caption=T(id)?.parentNode?.querySelector?.('.touch-caption');if(caption&&!caption.querySelector('.touch-power')){const power=document.createElement('i');power.className='touch-power';caption.appendChild(power);}}
 const configs={touchMelee:['✦','FLARE'],touchDash:['››','DASH'],touchReload:['↻','REKINDLE'],touchEnter:['◇','USE']};for(const[id,[icon,label]]of Object.entries(configs)){const el=T(id);el.innerHTML=`<strong>${icon}</strong><span class="touch-name">${label}</span><small class="touch-state">READY</small>`;el.style.setProperty('--ready','1');}
 for(const id of ['touchMelee','touchReload']){const el=T(id);on(el,'pointerdown',e=>{e.preventDefault();e.stopPropagation?.();el.classList.add('pressed');precisionTouchPointers[id]=e.pointerId;try{el.setPointerCapture(e.pointerId);}catch(_){ }if(G.state==='playing'&&!anyBlockingOverlay()){initAudio();if(id==='touchMelee')meleeQueued=true;else reloadQueued=true;}});for(const ev of ['pointerup','pointercancel','lostpointercapture'])on(el,ev,e=>{if(precisionTouchPointers[id]!==undefined&&e.pointerId!==undefined&&precisionTouchPointers[id]!==e.pointerId)return;delete precisionTouchPointers[id];el.classList.remove('pressed');});}
}
wireAnalogStick=function(id,kind){
 const stick=T(id),knob=stick.querySelector('.touch-knob'),pointerKey=kind+'Pointer',power=stick.parentNode?.querySelector?.('.touch-power');
 const paint=(dx,dy,mag)=>{knob.style.transform=`translate(${dx.toFixed(1)}px,${dy.toFixed(1)}px)`;stick.style.setProperty('--power',mag.toFixed(3));if(power)power.style.setProperty('--power',mag.toFixed(3));document.body.classList.toggle(kind==='aim'?'touch-aiming':'touch-moving',mag>.05);};
 const release=e=>{if(touchInput[pointerKey]!==null&&e?.pointerId!==undefined&&e.pointerId!==touchInput[pointerKey])return;touchInput[pointerKey]=null;touchInput[kind+'X']=0;touchInput[kind+'Y']=0;touchInput[kind+'Power']=0;if(kind==='aim'){touchInput.aimActive=false;touchInput.fire=false;}stick.classList.remove('active');paint(0,0,0);};
 const move=e=>{if(touchInput[pointerKey]!==e.pointerId)return;const samples=typeof e.getCoalescedEvents==='function'?e.getCoalescedEvents():null,q=samples?.length?samples[samples.length-1]:e,r=stick.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,max=Math.max(30,Math.min(r.width,r.height)*.37);let dx=q.clientX-cx,dy=q.clientY-cy,dist=Math.hypot(dx,dy);if(dist>max){dx*=max/dist;dy*=max/dist;dist=max;}const raw=clamp(dist/max,0,1),dead=kind==='move'?.065:.1,linear=raw<=dead?0:(raw-dead)/(1-dead),mag=kind==='move'?Math.pow(linear,1.08):Math.pow(linear,.92),nx=dist?dx/dist*mag:0,ny=dist?dy/dist*mag:0;touchInput[kind+'X']=nx;touchInput[kind+'Y']=ny;touchInput[kind+'Power']=mag;if(kind==='aim'){touchInput.aimActive=mag>.04;touchInput.fire=mag>.17;}paint(dx,dy,mag);};
 on(stick,'pointerdown',e=>{if(G.state!=='playing'||anyBlockingOverlay()||touchInput[pointerKey]!==null)return;e.preventDefault();e.stopPropagation?.();initAudio();touchInput[pointerKey]=e.pointerId;try{stick.setPointerCapture(e.pointerId);}catch(_){ }stick.classList.add('active');move(e);});on(stick,'pointermove',move);for(const ev of ['pointerup','pointercancel','lostpointercapture'])on(stick,ev,release);addEventListener('blur',release);document.addEventListener?.('visibilitychange',()=>{if(document.hidden)release();});
};
wireTouchAction=function(id,fn){const el=T(id);on(el,'pointerdown',e=>{if(precisionTouchPointers[id]!==undefined)return;e.preventDefault();e.stopPropagation?.();precisionTouchPointers[id]=e.pointerId;el.classList.add('pressed');try{el.setPointerCapture(e.pointerId);}catch(_){ }if(G.state==='playing'&&!anyBlockingOverlay()){initAudio();fn();}});for(const ev of ['pointerup','pointercancel','lostpointercapture'])on(el,ev,e=>{if(precisionTouchPointers[id]!==undefined&&e.pointerId!==undefined&&precisionTouchPointers[id]!==e.pointerId)return;delete precisionTouchPointers[id];el.classList.remove('pressed');});};
const precisionResetTouchInput=resetTouchInput;
resetTouchInput=function(){precisionResetTouchInput();touchInput.movePower=touchInput.aimPower=0;for(const id of ['touchMelee','touchDash','touchReload','touchEnter']){delete precisionTouchPointers[id];T(id)?.classList.remove('pressed');}document.body.classList.remove('touch-aiming','touch-moving');};
function setPrecisionTouchButton(id,ready,name,state){const el=T(id);if(!el)return;ready=clamp(ready,0,1);el.style.setProperty('--ready',ready.toFixed(3));el.classList.toggle('ready',ready>=.999);const n=el.querySelector('.touch-name'),s=el.querySelector('.touch-state');if(n)n.textContent=name;if(s)s.textContent=state;}
const precisionSyncWeaponHUD=syncWeaponHUD;
syncWeaponHUD=function(){precisionSyncWeaponHUD();const p=G.player;if(!p||!T('touchControls'))return;const flare=typeof activeForm==='function'?activeForm('flare'):{name:'Flare'},dash=typeof activeForm==='function'?activeForm('dash'):{name:'Dash'},primary=typeof activeForm==='function'?activeForm('primary'):{name:'Bolt'},fr=1-clamp(p.meleeCdT/Math.max(.01,MELEE.cooldown),0,1),dr=1-clamp(p.dashCdT/Math.max(.01,p.dashCd||BASE.dashCd),0,1),rr=p.reloadT>0?1-clamp(p.reloadT/Math.max(.01,p.reloadDuration||1),0,1):(p.ammo<p.magSize?1:0);setPrecisionTouchButton('touchMelee',fr,flare.name.toUpperCase().replace(' FLARE',''),fr>=1?'READY':p.meleeCdT.toFixed(1)+'s');setPrecisionTouchButton('touchDash',dr,dash.name.toUpperCase().replace(' DASH',''),dr>=1?'READY':p.dashCdT.toFixed(1)+'s');setPrecisionTouchButton('touchReload',rr,'REKINDLE',p.reloadT>0?'CHARGING':p.ammo<p.magSize?'READY':'FULL');setPrecisionTouchButton('touchEnter',1,'USE','READY');const cap=T('aimStickWrap')?.querySelector?.('.touch-caption b');if(cap)cap.textContent=primary.name.toUpperCase().replace('EMBER ','').slice(0,12);};
const precisionDrawCombatFX=drawCombatFX;
drawCombatFX=function(ctx){precisionDrawCombatFX(ctx);const p=G.player;if(!p||!document.body.classList.contains('touch')||G.state!=='playing')return;const t=save.motion?0:G.tAll;ctx.save();ctx.globalCompositeOperation='lighter';if(touchInput.aimActive){const a=aimAngle(),mag=touchInput.aimPower||Math.hypot(touchInput.aimX,touchInput.aimY),r=68+mag*46,x=p.x+Math.cos(a)*r,y=p.y+Math.sin(a)*r;ctx.strokeStyle=touchInput.fire?'#ffd18b':'#afc9d5';ctx.globalAlpha=.34+mag*.34;ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(p.x+Math.cos(a)*25,p.y+Math.sin(a)*25);ctx.lineTo(x-Math.cos(a)*10,y-Math.sin(a)*10);ctx.stroke();ctx.save();ctx.translate(x,y);ctx.rotate(t*.75);for(let i=0;i<4;i++){ctx.rotate(Math.PI/2);ctx.beginPath();ctx.moveTo(8,0);ctx.lineTo(15+mag*5,0);ctx.stroke();}ctx.restore();}if((touchInput.movePower||0)>.12){const a=Math.atan2(touchInput.moveY,touchInput.moveX),r=25;ctx.strokeStyle='#9fe6ed';ctx.globalAlpha=.22+.18*(touchInput.movePower||0);ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,r,a-.42,a+.42);ctx.stroke();}ctx.restore();};
installPrecisionTouch();
